Map<String, String> arabicLanguage = <String, String>{
  'unknown_failure': 'خطا غير معروف , برجاء المحاوله مجددا',
  'payment_failure': 'حدث خطأ في عملية الدفع , برجاء المحاوله مجددا',
  'timeout_failure': 'هذا الطلب ياخذ وقت طويل , برجاء المحاوله مجددا',
  'internal_server_failure': 'خطا في الخادم , برجاء المحاوله مجددا في وقت لاحق',
  'unauthorized_failure': 'غير مصرح لك بتنفيذ هذا الطلب',
  'network_failure':
      'خطا في الاتصال , برجاء التاكد من الاتصال بالانترنت والمحاوله مجددا',
  'parsing_failure': 'خطا في تحليل البيانات',
  'forbidden_failure': 'غير مصرح لك بتنفيذ هذا الطلب',
  'locale_database_failure': 'خطأ في قاعدة البيانات',
  'onboarding_1_title': 'مرحبا بك في\nباك كمفورت',
  'onboarding_1_subtitle': 'مكان لشراء وبيع السلع الحقيقية بسهولة وبساطة',
  'onboarding_2_title': 'ابحث عن اي شيء هنا',
  'onboarding_2_subtitle': 'ابحث عن ملايين من العناصر التي تريد',
  'onboarding_3_title': 'تسوق بسهولة',
  'onboarding_3_subtitle': 'مع موبايلك فقط تستطيع البحث عن كل شيء',
  'onboarding_4_title': 'المعاملات موثوقة',
  'onboarding_4_subtitle': 'نحن نضمن لك امان بياناتك',
  'sign_in': 'تسجيل الدخول',
  'sign_up': 'انشاء حساب',
  'start': 'ابدأ',
  'update_title': 'تحديث التطبيق',
  'update_desc': 'الرجاء تحديث التطبيق للحصول على النسخة الجديدة',
  'update_now': 'تحديث الآن',
  'call_us': 'اتصل بنا',
  'shop_now': 'تسوق الان',
  'rs': '@price ر.س',
  'categories': 'الفئات',
  'product': 'منتج',
  'error_title': 'عفوا ، لقد حدث خطأ ما',
  'retry': 'اعادة المحاولة',
  'error_loading_more': 'خطأ في تحميل المزيد',
  'no_products': 'عفوا ، لا توجد منتجات',
  'search': 'بحث',
  'sort_by': 'ترتيب حسب',
  'position': 'الترتيب',
  'desc': 'من الاعلي الي الاقل',
  'asc': 'من الاقل الي الاعلي',
  'all_filters': 'كل التصفيات',
  'no_filters': 'لا يوجد تصفيات',
  'show_results': 'اظهار النتائج',
  'reset': 'اعادة تعيين',
  'end_of_results': 'نهاية النتائج',
  'products_search': 'ابحث عن المنتجات',
  'type_to_search': 'قم بكتابة شيء للبحث',
  'no_search': 'عفوا ، لا يوجد بحث',
  'product_details': 'تفاصيل المنتج',
  'not_found': 'لم نستطع ايجاد بيانات هذا الطلب',
  'type': 'النوع',
  'model': 'الموديل',
  'sku': 'الكود',
  'discount': 'خصم',
  'view_more': 'اظهار المزيد',
  'error_loading_reviews': 'خطأ في تحميل المراجعات',
  'description': 'الوصف',
  'additional_info': 'معلومات اضافية',
  'specifications': 'المواصفات',
  'review_summery': 'ملخص المراجعات',
  'view_all_reviews': 'عرض جميع المراجعات',
  'reviews_base_on': 'اعتمادا علي @count مراجعة',
  'users_reviews': 'مراجعات المستخدمين',
  'experts_reviews': 'مراجعات الخبراء',
  'no_reviews': 'عفوا , لا توجد مراجعات',
  'similar_products': 'منتجات مماثله لنفس المنتج',
  'sold_with': 'يباع معها ايضا',
  'buy_now': 'اشتري الان',
  'my_account': 'حسابي',
  'others': 'اخرى',
  'faq': 'الاسئلة الشائعة',
  'contact_us': 'اتصل بنا',
  'terms_and_conditions': 'الشروط والاحكام',
  'privacy_policy': 'سياسة الخصوصية',
  'about_app': 'عن التطبيق',
  'app_language': 'لغة التطبيق',
  'share_app': 'مشاركة التطبيق',
  'account_details': 'تفاصيل الحساب',
  'my_profile': 'الملف الشخصي',
  'addresses': 'العناوين',
  'my_orders': 'طلباتي',
  'delete_account': 'حذف الحساب',
  'logout': 'تسجيل الخروج',
  'email_login': 'التسجيل بالبريد',
  'phone_login': 'التسجيل بالهاتف',
  'login_with_email': 'سجل الدخول ببريدك الالكتروني',
  'login_with_phone': 'سجل الدخول برقم هاتفك',
  'if_you_have_an_account': 'اذا كان لديك حساب, ',
  'you_can_create_an_account': 'يمكنك تسجيل حساب جديد, ',
  'register_message':
      'للاستمتاع بفوائد الموقع، مثل تتبع الطلبات وتسجيل المنتجات في المفضلة الخاصة بك',
  'required_field': 'هذا الحقل مطلوب',
  'invalid_name': 'الاسم غير صالح',
  'invalid_email': 'البريد غير صالح',
  'invalid_phone_number': 'رقم الهاتف غير صالح',
  'invalid_password': 'كلمة المرور غير صالحة',
  'password_mismatch': 'كلمة المرور غير متطابقة',
  'send_otp': 'ارسال رمز التحقق',
  'have_no_account': 'ليس لديك حساب؟ ',
  'have_account': 'هل لديك حساب؟ ',
  'email': 'البريد الالكتروني',
  'password': 'كلمة المرور',
  'confirm_password': 'تأكيد كلمة المرور',
  'forgot_password': 'نسيت كلمة المرور؟',
  'phone': 'رقم الهاتف',
  'back': 'رجوع',
  'error': 'خطأ',
  'session_ended': 'انتهت صلاحية الجلسة',
  'verify': 'تحقق',
  'enter_otp': 'ادخل رمز التحقق',
  'first_name': 'الاسم الاول',
  'last_name': 'الاسم الاخير',
  'agree_to': 'انا وافق على ',
  'success_register': 'تم التسجيل بنجاح , الرجاء تسجيل الدخول',
  'deleted_account_error':
      'تم حذف هذا الحساب برجاء التسجيل مجددا بهذة البيانات',
  'delete': 'حذف',
  'delete_account_success': 'تم حذف الحساب بنجاح , نرجو رؤيتك مجددا قريبا',
  'delete_account_message': 'هل تريد حذف هذا الحساب ؟',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'enter_phone': 'برجاء إدخال رقم الهاتف. ',
  'enter_email': 'برجاء إدخال البريد الإلكتروني. ',
  'enter_phone_message':
      'سنقوم بإرسال رمز إلى رقم الهاتف لإعادة تعيين كلمة المرور الخاصة بك',
  'enter_email_message':
      'سنقوم بإرسال بريد إلكتروني لإعادة تعيين كلمة المرور الخاصة بك',
  'change_password': 'تغيير كلمة المرور',
  'success': 'نجاح',
  'done': 'تم',
  'reset_password_email_sent':
      'تم ارسال بريد لاعادة تعيين كلمة المرور برجاء التحقق من بريدك',
  'shopping_cart': 'سلة المشتريات',
  'empty_cart_title': 'للاسف ، لايوجد منتجات في السلة',
  'empty_cart_message': 'اضف منتاجات الى سلة المشتريات لاكمال عملية الشراء',
  'cart_error': 'حدث خطأ في استرجاع السلة, ',
  'add_to_cart': 'اضف للسلة',
  'out_of_stock': 'غير متوفر',
  'added_to_cart': 'تمت الاضافة الي سلة المشتريات',
  'all_qty_in_cart': 'كل الكمية في سلة المشتريات',
  'remove_cart_item': 'هل تريد حذف العنصر من سلة المشتريات؟',
  'go_to_payment': 'الذهاب للدفع',
  'installment1': ' دفعات ',
  'installment2': 'بلا فوائد بقيمة ',
  'installment3': 'بدون رسوم، ومتوافقة مع أحكام الشريعة ',
  'voucher_success': 'تم تطبيق الخصم بنجاح',
  'voucher': 'بطاقه الخصم',
  'add_coupon': 'اضافة كوبون',
  'add_code_message': 'ادخل الكود ، للحصول علي الخصم',
  'add_phone_number': 'ادخل رقم الهاتف',
  'invalid_number': 'رقم غير صالح',
  'voucher_amount': 'قيمة الخصم',
  'success_update_addresses': 'تم تحديث العناوين بنجاح',
  'choose_city': 'اختر مدينتك',
  'street': 'الشارع',
  'add_address': 'اضافة عنوان',
  'edit_address': 'تعديل عنوان',
  'post_code': 'الرمز البريدي',
  'no_addresses_title': 'عفوا, لايوجد عناوين',
  'no_addresses_message': 'اضف عناوين لعرضها هنا',
  'loading': 'جاري التحميل',
  'error_get_cities': 'حدث خطاء في استرجاع المدن ',
  'add_or_edit_address': 'اضافه / تعديل العنوان',
  'edit': 'تعديل',
  'delete_address_message': 'هل تريد حذف العنوان؟',
  'set_default': 'تعيين كافتراضي',
  'default_address': 'العنوان الافتراضي',
  'other_addresses': 'عناوين اخرى',
  'default': 'افتراضي',
  'checkout': 'الدفع',
  'payment_method': 'طريقة الدفع',
  'order_details': 'تفاصيل الطلب',
  'order_success_message': 'تم اتمام عملية الشراء بنجاح',
  'order_failure_message': 'عذرا ، حدث خطاء في عملية الشراء',
  'confirm': 'تاكيد',
  'credit_card': 'بطاقه الائتمان',
  'saved_cards': 'بطاقات محفوظة',
  'delete_voucher': 'هل انت متأكد انك تريد حذف هذا الخصم؟',
  'thank_you': 'شكرا لك @name',
  'success_order_message':
      'تم إرسال رسالة تأكيد بالبريد الإلكتروني @email وتم إرسال رسالة تأكيد قصيرة إلى @phone سيتم تسليم طلبك خلال 2 - 5 أيام عمل كحد أقصى من خلال شريك التوصيل لدينا بين الساعة 9 صباحًا حتى 5 مساءً باستثناء أيام الجمعة والعطلات الرسمية. بمجرد الشحن، ستتلقى رسالة تأكيد بالبريد الإلكتروني / رسالة نصية قصيرة تحتوي على معلومات التتبع.',
  'order_number': 'رقم الطلب: @id',
  'hurray': 'تهانينا',
  'promo_code_message':
      'بما أنك اشتريت @product_name، فأنت مؤهل للحصول على خصم إضافي بنسبة @discount % على هذه المنتجات. استخدم رمز القسيمة @coupon الذي يُعتبر صالحاً حتى @valid_till.',
  'order_date': 'تاريخ الطلب',
  'order_status': 'حالة الطلب',
  'name': 'الاسم',
  'billing_details': 'تفاصيل الدفع',
  'payment_and_shipping': 'الدفع والشحن',
  'tracking_number': 'رقم التتبع',
  'subtotal': 'المجموع الفرعي',
  'shipping_price': 'سعر الشحن',
  'shipping': 'الشحن',
  'grand_total': 'المجموع الكلي',
  'tax': 'الضريبة',
  'continue_shopping': 'اكمل التسوق',
  'print_order': 'طباعة فاتورة الطلب',
  'old_password': 'كلمة المرور القديمة',
  'new_password': 'كلمة المرور الجديدة',
  'change_email_success': 'تم تغيير البريد الالكتروني بنجاح',
  'change_name_success': 'تم تغيير الاسم بنجاح',
  'change_password_success': 'تم تغيير كلمة المرور بنجاح',
  'change_name': 'تغيير الاسم',
  'change_email': 'تغيير البريد الالكتروني',
  'new_email': 'البريد الالكتروني الجديد',
  'favorites': 'المفضلة',
  'delete_from_favorites': 'هل انت متاكد انك تريد حذف هذا من المفضلة؟',
  'empty_favorites_title': 'عفوا, لا يوجد منتجات في المفضلة',
  'empty_favorites_message':
      'أضف منتاجات مفضلتك وسوف تظهر هنا لك في هذه الصفحة',
  'favorites_error': 'حدث خطأ في الحصول على المفضلة, ',
  'no_orders_title': 'عفوا, لا يوجد طلبات',
  'no_orders_message': 'أضف طلباتك وسوف تظهر هنا لك في هذه الصفحة',
  'code_confirmed': 'تم تأكيد الكود',
  'pending': 'في الانتظار',
  'pending_payment': 'في انتظار الدفع',
  'processing': 'جاري المعالجة',
  'processed': 'تم المعالجة',
  'shipped': 'تم الشحن',
  'delivered': 'تم التوصيل',
  'canceled': 'تم الالغاء',
  'returned': 'تم الارجاع',
  'unknown': 'غير معروف',
  'total_price': 'الاجمالي: @price',
  'products_qty': '@qty منتج',
  'return_order_success': 'تم ارسال طلب الارجاع بنجاح',
  'delivery_method': 'طريقة التوصيل',
  'products': 'المنتجات',
  'return_order': 'ارجاع الطلب',
  'return_selected_products': 'ارجاع المنتجات المحددة',
  'rate_product': 'قيم المنتج',
  'your_review_title': 'عنوان مراجعتك',
  'your_review_description': 'تفاصيل المراجعة',
  'success_add_review': 'تم اضافة مراجعتك بنجاح',
  'branches': 'الفروع',
  'follow_us_on': 'تابعنا على',
  'have_problem': 'هل لديك مشكلة؟',
  'subject': 'الموضوع',
  'details': 'تفاصيل',
  'send': 'ارسال',
  'success_send_message': 'تم ارسال الرسالة بنجاح',
  'compare': 'مقارنة',
  'price': 'السعر',
  'change_language': 'تغيير اللغة',
  'cancel': 'الغاء',
  'notifications': 'الاشعارات',
  'no_notifications_title': 'عفوا, لا يوجد اشعارات',
  'no_notifications_message': 'عند وصول اشعارات سوف تظهر هنا لك في هذه الصفحة',
  'no_items': 'لا يوجد عناصر',
  'get_reviews_error': 'حدث خطأ في الحصول على المراجعات',
  'shop_by_category': 'تسوق حسب الفئة',
  'invalid_cart_error': 'السلة غير صالحة ، الرجاء المحاولة مرة اخرى',
  'config_not_available': 'هذا الاختيار غير متاح',
  'size': 'القياس',
  'color': 'اللون',
  'select_options': 'حدد خياراتك',
  'download_invoice_error': 'حدث خطأ في تنزيل الفاتورة',
  'open_invoice_error': 'حدث خطأ في فتح الفاتورة',
  'sign_in_or_sign_up': 'تسجيل دخول / حساب جديد',
  'buy_with_product': 'اشتري ال @count منتجات معاه بسعر @price',
  'buy_with_no_products': 'حدد منتجات لشراءها مع المنتج',
  'home': 'المنزل',
  'shipping_method': 'طريقة الشحن',
  'add_pickup_info': 'اضافة معلومات الاستلام',
  'qty': 'الكمية',
  'total': 'الاجمالي',
  'view_less': 'اظهار اقل',
  'branch': 'الفرع',
  'date': 'التاريخ',
  'time_from': 'الوقت من',
  'tome_to': 'الوقت الي',
  'category_details': 'تفاصيل الفئة',
  'end_payment_message':
      'أذا قمت بأغلاق هذه الصفحة لن تستطيع اكمال عملية الدفع',
  'close': 'اغلاق',
  'welcome': 'مرحبا',
  'profile_error': 'خطأ تحميل بياناتك',
  'need_help': 'لديك مشكلة؟',
  'whatsapp': 'واتساب',
  'time': 'الوقت',
  'from': 'من',
  'to': 'الي',
  'ok': 'حسنا',
  'mail': 'البريد',
  'view_cart': 'الذهاب للسلة',
  'need_help_message':
      'فريقنا هنا لمساعدتك في أي شيء تحتاجه. يمكنك دائمًا التواصل معنا من خلال فريق الدعم الخاص بنا. نحن دائمًا سعداء بمساعدتك.',
  'tabby': 'تابي',
  'stc': 'STC',
  'madfu': 'مدفوع',
  'tamara': 'تمارا',
  'cashOnDelivery': 'الدفع عند الاستلام',
  'payfortSavedCard': 'بطاقة الائتمان المحفوظة',
  'payfortCreditCard': 'بطاقة الائتمان',
  'applePay': 'ابل باي',
  'aramexCashOnDelivery': 'اراميكس الدفع عند الاستلام',
  'card_number': 'رقم البطاقة',
  'expiration_date': 'تاريخ الانتهاء',
  'cvv': 'CVV',
  'card_holder': 'اسم صاحب البطاقة',
  'recommended': 'موصى به',
  'card_number_validator': 'الرجاء ادخال رقم بطاقة صحيح',
  'expiry_date_validator': 'الرجاء ادخال تاريخ صحيح',
  'cvv_validator': 'الرجاء ادخال CVV صحيح',
  'card_holder_validator': 'الرجاء ادخال اسم صحيح',
  'close_payment_message':
      'أذا قمت بأغلاق هذه الصفحة لن تستطيع اكمال عملية الدفع',
  'same_old_and_new_password':
      'يجب أن لا يكون كلمة المرور الجديدة هي نفس كلمة المرور القديمة، يرجى إدخال كلمة مرور مختلفة.',
  'view_on_map': 'اظهار على الخريطة',
  'all': 'الكل',
};
