Map<String, String> englishLanguage = {
  'unknown_failure': 'Unknown Failure, Please try again',
  'payment_failure':
      'An error occurred while processing your payment, Please try again',
  'timeout_failure': 'This request took too long, Please try again',
  'internal_server_failure': 'Internal Server Failure, Please try again later',
  'unauthorized_failure': 'Unauthorized User',
  'network_failure':
      'Network Connection Failure, Please check your internet and try again',
  'parsing_failure': 'Data Parsing Failure, Please try again later',
  'forbidden_failure': 'Forbidden Failure',
  'locale_database_failure': 'Locale Database Failure',
  'onboarding_1_title': 'WELCOME TO\nBACK COMFORT',
  'onboarding_1_subtitle':
      'The place to buy and sell online is easy and practical',
  'onboarding_2_title': 'Find any item here',
  'onboarding_2_subtitle': 'Find millions of items you want very easily',
  'onboarding_3_title': 'Shopping easier',
  'onboarding_3_subtitle': 'Only with your smartphone you can find everything',
  'onboarding_4_title': 'Secured Transactions',
  'onboarding_4_subtitle': 'We guarantee all your data that you provide',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'start': 'Start',
  'update_title': 'Update App',
  'update_desc': 'Please Update your app to the latest version',
  'update_now': 'Update Now',
  'call_us': 'Call Us',
  'shop_now': 'Shop Now',
  'rs': '@price RS',
  'categories': 'Categories',
  'product': 'Product',
  'error_title': 'Sorry, An Error Has Happened',
  'retry': 'Try Again',
  'error_loading_more': 'Error Loading More',
  'no_products': 'Sorry, No Products Found',
  'search': 'Search',
  'sort_by': 'Sort By',
  'position_desc': 'Position',
  'desc': 'From High To Low',
  'asc': 'From Low To High',
  'all_filters': 'All Filters',
  'no_filters': 'No Filters',
  'show_results': 'Show Results',
  'reset': 'Reset',
  'end_of_results': 'End Of Results',
  'products_search': 'Search Products',
  'type_to_search': 'Type Something To Search',
  'no_search': 'Sorry, No Search Found',
  'product_details': 'Product Details',
  'not_found': 'Can\'t find any data for this request',
  'type': 'Type',
  'model': 'Model',
  'sku': 'SKU',
  'discount': 'Discount',
  'view_more': 'View More',
  'error_loading_reviews': 'Error Loading Reviews',
  'description': 'Description',
  'additional_info': 'Additional Info',
  'specifications': 'Specifications',
  'review_summery': 'Review Summery',
  'view_all_reviews': 'View All Reviews',
  'reviews_base_on': 'Based on @count Reviews',
  'users_reviews': 'Users Reviews',
  'experts_reviews': 'Experts Reviews',
  'no_reviews': 'Sorry, No Reviews Found',
  'similar_products': 'Similar Products',
  'sold_with': 'Always sold with',
  'buy_now': 'Buy Now',
  'my_account': 'My Account',
  'create_account': 'Create Account',
  'others': 'Others',
  'faq': 'FAQ',
  'contact_us': 'Contact Us',
  'terms_and_conditions': 'Terms & Conditions',
  'privacy_policy': 'Privacy Policy',
  'about_app': 'About App',
  'app_language': 'App Language',
  'share_app': 'Share App',
  'account_details': 'Account Details',
  'my_profile': 'Personal Profile',
  'addresses': 'Addresses',
  'my_orders': 'My Orders',
  'delete_account': 'Delete Account',
  'logout': 'Logout',
  'email_login': 'Email Login',
  'phone_login': 'Phone Login',
  'login_with_email': 'Login with your Email',
  'login_with_phone': 'Login with your Phone',
  'if_you_have_an_account': 'If you have an account, ',
  'you_can_create_an_account': 'you can create a new account, ',
  'register_message':
      'To enjoy the site’s benefits, such as tracking orders and registering products in your favorites',
  'required_field': 'Required Field',
  'invalid_name': 'Invalid Name',
  'invalid_email': 'Invalid Email',
  'invalid_phone_number': 'Invalid Phone Number',
  'invalid_password': 'Invalid Password',
  'password_mismatch': 'Password Mismatch',
  'send_otp': 'Send OTP',
  'have_no_account': 'Don\'t have an account? ',
  'have_account': 'Already have an account? ',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'forgot_password': 'Forgot Password',
  'phone': 'Phone',
  'back': 'Back',
  'error': 'Error',
  'session_ended': 'Your Session Ended',
  'verify': 'Verify',
  'enter_otp': 'Enter OTP',
  'first_name': 'First Name',
  'last_name': 'Last Name',
  'agree_to': 'I Agree to the ',
  'success_register': 'Successfully Registered, Please Login',
  'deleted_account_error':
      'This account was deleted please register again with this data',
  'delete': 'Delete',
  'delete_account_success':
      'Account Deleted Successfully, We wish to see you again soon',
  'delete_account_message': 'Are you sure you want to delete your account ?',
  'reset_password': 'Reset Password',
  'enter_phone': 'Please enter your phone. ',
  'enter_email': 'Please enter your email. ',
  'enter_phone_message':
      'We will send a code to your phone to reset your password.',
  'enter_email_message': 'We will send you an email to reset your password',
  'change_password': 'Change password',
  'success': 'Success',
  'done': 'Done',
  'reset_password_email_sent':
      'Reset password email sent to your mailbox please check it',
  'shopping_cart': 'Shopping Cart',
  'empty_cart_title': 'Sorry, Your Cart Is Empty',
  'empty_cart_message': 'Add items to your cart to continue shopping',
  'cart_error': 'An Error happen with your cart, ',
  'add_to_cart': 'Add To Cart',
  'out_of_stock': 'Out Of Stock',
  'added_to_cart': 'Added To Your Cart',
  'all_qty_in_cart': 'All Quantity In Cart',
  'remove_cart_item': 'Do you want to delete this item from cart?',
  'go_to_payment': 'Go To Payment',
  'installment1': ' payments ',
  'installment2': ' with out benefits with value ',
  'installment3': ' without fees and compatible with the provisions of sharia',
  'voucher_success': 'Voucher Applied Successfully',
  'voucher': 'Voucher Code',
  'add_coupon': 'Add Coupon',
  'add_code_message': 'Add Code to get discount',
  'add_phone_number': 'Add Phone Number',
  'invalid_number': 'Invalid Number',
  'voucher_amount': 'Voucher Amount',
  'success_update_addresses': 'Success Update Addresses',
  'choose_city': 'Choose your city',
  'street': 'Street',
  'add_address': 'Add Address',
  'edit_address': 'Edit Address',
  'post_code': 'Post Code',
  'no_addresses_title': 'Sorry, No Addresses Found',
  'no_addresses_message': 'Add Addresses To view them here',
  'loading': 'Loading...',
  'error_get_cities': 'Error get cities ',
  'add_or_edit_address': 'Add / Edit Address',
  'edit': 'Edit',
  'delete_address_message': 'Are you sure you want to delete this address ?',
  'set_default': 'Set Default',
  'default_address': 'Default Address',
  'other_addresses': 'Other Addresses',
  'default': 'Default',
  'checkout': 'Checkout',
  'payment_method': 'Payment Method',
  'order_details': 'Order Details',
  'order_success_message': 'Your order has been successfully placed',
  'order_failure_message': 'Your order has been failed, please try again',
  'confirm': 'Confirm',
  'credit_card': 'Credit Card',
  'saved_cards': 'Saved Cards',
  'delete_voucher': 'Are you sure you want to delete this voucher?',
  'thank_you': 'Thank you @name',
  'success_order_message':
      'A confirmation email has been sent to @email, and a short confirmation message has been sent to @phone. Your order will be delivered within 2 - 5 working days at most through our delivery partner between 9 am and 5 pm, excluding Fridays and public holidays. Once shipped, you will receive a confirmation email/text message containing tracking information.',
  'order_number': 'Your Order Number is: @id',
  'hurry': 'Hurray',
  'promo_code_message':
      'Since you bought @product_name, you are eligible to get @discount % additional discount on these products. Use the coupon code @coupon which is valid upto @valid_till.',
  'order_date': 'Order Date',
  'order_status': 'Order Status',
  'name': 'Name',
  'billing_details': 'Billing Details',
  'payment_and_shipping': 'Payment And Shipping',
  'tracking_number': 'Tracking Number',
  'subtotal': 'Subtotal',
  'shipping_price': 'Shipping Price',
  'shipping': 'Shipping',
  'grand_total': 'Grand Total',
  'tax': 'tax',
  'continue_shopping': 'Continue Shopping',
  'print_order': 'Print Order Invoice',
  'old_password': 'Old Password',
  'new_password': 'New Password',
  'change_email_success': 'Your email has been changed successfully',
  'change_name_success': 'Your name has been changed successfully',
  'change_password_success': 'Your password has been changed successfully',
  'change_name': 'Change Name',
  'change_email': 'Change Email',
  'new_email': 'New Email',
  'favorites': 'Favorites',
  'delete_from_favorites':
      'Are you sure you want to delete this product from favorites?',
  'empty_favorites_title': 'Sorry, No Products Found',
  'empty_favorites_message': 'Add Products To Your Favorites To view them here',
  'favorites_error': 'An Error happen When get favorites, ',
  'no_orders_title': 'Sorry, No Orders Found',
  'no_orders_message': 'Add Orders To view them here',
  'code_confirmed': 'Code Confirmed',
  'pending': 'Pending',
  'pending_payment': 'Pending Payment',
  'processing': 'Processing',
  'processed': 'Processed',
  'shipped': 'Shipped',
  'delivered': 'Delivered',
  'canceled': 'Canceled',
  'returned': 'Returned',
  'total_price': 'Total: @price',
  'products_qty': '@qty Product',
  'return_order_success': 'Your return Order has been successfully placed',
  'delivery_method': 'Delivery Method',
  'products': 'Products',
  'return_order': 'Return Order',
  'return_selected_products': 'Return Selected Products',
  'rate_product': 'Rate Product',
  'your_review_title': 'Your Review Title',
  'your_review_description': 'Your Review Description',
  'success_add_review': 'Your Review has been successfully added',
  'branches': 'Branches',
  'follow_us_on': 'Follow Us On',
  'have_problem': 'Have A Problem?',
  'subject': 'Subject',
  'details': 'Details',
  'send': 'Send',
  'success_send_message': 'Your Message has been successfully sent',
  'compare': 'Compare',
  'price': 'Price',
  'change_language': 'Change Language',
  'cancel': 'Cancel',
  'notifications': 'Notifications',
  'no_notifications_title': 'Sorry, No Notifications Found',
  'no_notifications_message':
      'when you get notifications, they will appear here',
  'no_items': 'No Items Found',
  'get_reviews_error': 'An Error happen When get reviews ',
  'shop_by_category': 'Shop By Category',
  'invalid_cart_error': 'Invalid Cart, Please Try Again',
  'config_not_available': 'This Option is not available',
  'size': 'Size',
  'color': 'Color',
  'select_options': 'Select Your Options',
  'download_invoice_error': 'An Error happen When download invoice',
  'open_invoice_error': 'An Error happen When open invoice',
  'signInOrSignUp': 'Sign In / Create Account',
  'buy_with_product': 'Buy With @count Products For @price',
  'buy_with_no_products': 'Select Products To Buy With Product',
  'home': 'Home',
  'shipping_method': 'Shipping Method',
  'add_pickup_info': 'Add Pickup Information',
  'qty': 'Qty',
  'total': 'Total',
  'view_less': 'View Less',
  'branch': 'Branch',
  'date': 'Date',
  'time_from': 'Time From',
  'tome_to': 'Time To',
  'category_details': 'Category Details',
  'end_payment_message':
      'If you closed this page you will not be able to finish your payment process',
  'close': 'Close',
  'welcome': 'Welcome',
  'profile_error': 'Error get profile',
  'need_help': 'Need Help?',
  'whatsapp': 'Whatsapp',
  'time': 'Time',
  'from': 'From',
  'to': 'To',
  'ok': 'Ok',
  'mail': 'Mail',
  'view_cart': 'View Cart',
  'need_help_message':
      'our team is here to help you with anything you need. You can always reach us through our support team. We are always happy to help.',
  'tabby': 'Tabby',
  'stc': 'STC',
  'tamara': 'Tamara',
  'madfu': 'Madfu',
  'cashOnDelivery': 'Cash On Delivery',
  'payfortSavedCard': 'Saved Credit Card',
  'payfortCreditCard': 'Credit Card',
  'applePay': 'Apple Pay',
  'aramexCashOnDelivery': 'Aramex Cash On Delivery',
  'card_number': 'Card Number',
  'expiration_date': 'Expire Date',
  'cvv': 'CVV',
  'card_holder': 'Card Holder',
  'recommended': 'Recommended',
  'card_number_validator': 'Please Enter valid Card Number',
  'expiry_date_validator': 'Please Enter valid Date',
  'cvv_validator': 'Please Enter valid CVV',
  'card_holder_validator': 'Please Enter Valid Name',
  'close_payment_message':
      'If you close this page you will not be able to complete your payment',
  'same_old_and_new_password':
      'New password can not be same as old password, please enter different password',
  'view_on_map': 'View On Map',
  'all': 'All',
};
